-- MySQL Script generated by MySQL Workbench
-- 03/30/16 17:23:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CentroDeCalculo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CentroDeCalculo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CentroDeCalculo` DEFAULT CHARACTER SET utf8 ;
USE `CentroDeCalculo` ;

-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Rol` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Rol` (
  `Rol` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Carrera` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Carrera` (
  `Carrera` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_Creacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Carrera`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Area` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Area` (
  `Area` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Area`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Ciclo` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Ciclo` (
  `Anio` INT NOT NULL,
  `Ciclo` INT NOT NULL,
  PRIMARY KEY (`Anio`, `Ciclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Salon` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Salon` (
  `Salon` INT NOT NULL,
  `Edificio` VARCHAR(4) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Audiovisual` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Salon`, `Edificio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Escuela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Escuela` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Escuela` (
  `Escuela` INT NOT NULL AUTO_INCREMENT,
  `FechaFundacion` DATE NULL,
  `HoraApertura` TIME NOT NULL,
  `HoraCierre` TIME NOT NULL,
  `Carrera` INT NOT NULL,
  `Salon` INT NOT NULL,
  `Edificio` VARCHAR(4) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Escuela`),
  CONSTRAINT `fk_Carrera`
    FOREIGN KEY (`Carrera`)
    REFERENCES `CentroDeCalculo`.`Carrera` (`Carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salon`
    FOREIGN KEY (`Salon` , `Edificio`)
    REFERENCES `CentroDeCalculo`.`Salon` (`Salon` , `Edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Plan` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Plan` (
  `Anio` INT NOT NULL,
  `Ciclo` INT NOT NULL,
  `Escuela` INT NOT NULL,
  PRIMARY KEY (`Anio`, `Ciclo`, `Escuela`),
  CONSTRAINT `fk_Ciclo_Anio`
    FOREIGN KEY (`Anio` , `Ciclo`)
    REFERENCES `CentroDeCalculo`.`Ciclo` (`Anio` , `Ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Escuela`
    FOREIGN KEY (`Escuela`)
    REFERENCES `CentroDeCalculo`.`Escuela` (`Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Curso` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Curso` (
  `Curso` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Curso`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Pensum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Pensum` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Pensum` (
  `Creditos` INT NOT NULL,
  `Plan_Anio` INT NOT NULL,
  `Plan_Ciclo` INT NOT NULL,
  `Plan_Escuela` INT NOT NULL,
  `Curso_Curso` INT NOT NULL,
  PRIMARY KEY (`Plan_Anio`, `Plan_Ciclo`, `Plan_Escuela`, `Curso_Curso`),
  CONSTRAINT `fk_Pensum_Plan1`
    FOREIGN KEY (`Plan_Anio` , `Plan_Ciclo` , `Plan_Escuela`)
    REFERENCES `CentroDeCalculo`.`Plan` (`Anio` , `Ciclo` , `Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pensum_Curso1`
    FOREIGN KEY (`Curso_Curso`)
    REFERENCES `CentroDeCalculo`.`Curso` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`PreRequisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`PreRequisito` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`PreRequisito` (
  `CursoPreRequisito` INT NOT NULL,
  `Escuela` INT NOT NULL,
  `Pensum_Plan_Anio` INT NOT NULL,
  `Pensum_Plan_Ciclo` INT NOT NULL,
  `Pensum_Plan_Escuela` INT NOT NULL,
  `Pensum_Curso_Curso` INT NOT NULL,
  PRIMARY KEY (`CursoPreRequisito`, `Escuela`, `Pensum_Plan_Anio`, `Pensum_Plan_Ciclo`, `Pensum_Plan_Escuela`, `Pensum_Curso_Curso`),
  CONSTRAINT `fk_Curso`
    FOREIGN KEY (`CursoPreRequisito`)
    REFERENCES `CentroDeCalculo`.`Curso` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PreRequisito_Pensum1`
    FOREIGN KEY (`Pensum_Plan_Anio` , `Pensum_Plan_Ciclo` , `Pensum_Plan_Escuela` , `Pensum_Curso_Curso`)
    REFERENCES `CentroDeCalculo`.`Pensum` (`Plan_Anio` , `Plan_Ciclo` , `Plan_Escuela` , `Curso_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`TipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`TipoUsuario` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`TipoUsuario` (
  `Tipo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`EmpresaTelefonica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`EmpresaTelefonica` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`EmpresaTelefonica` (
  `Telefonica` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telefonica`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Usuario` (
  `Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Telefono` VARCHAR(8) NOT NULL,
  `Telefonica` INT NOT NULL,
  `DPI` VARCHAR(15) NULL,
  PRIMARY KEY (`Usuario`),
  CONSTRAINT `fk_Telefonica`
    FOREIGN KEY (`Telefonica`)
    REFERENCES `CentroDeCalculo`.`EmpresaTelefonica` (`Telefonica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Detalle_TipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Detalle_TipoUsuario` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Detalle_TipoUsuario` (
  `Codigo` INT NOT NULL,
  `Usuario` INT NOT NULL,
  `Tipo` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`),
  CONSTRAINT `fk_TipoUsuario`
    FOREIGN KEY (`Tipo`)
    REFERENCES `CentroDeCalculo`.`TipoUsuario` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario`
    FOREIGN KEY (`Usuario`)
    REFERENCES `CentroDeCalculo`.`Usuario` (`Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`ContratacionCatedratico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`ContratacionCatedratico` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`ContratacionCatedratico` (
  `Catedratico` INT NOT NULL,
  `Colegiado` INT NOT NULL,
  `FechaIngreso` DATE NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  `Titual` TINYINT(1) NOT NULL,
  `FechaEgreso` DATE NULL,
  PRIMARY KEY (`Catedratico`),
  CONSTRAINT `fk_Catedratico`
    FOREIGN KEY (`Catedratico`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`NivelCatedratico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`NivelCatedratico` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`NivelCatedratico` (
  `Nivel` INT NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  `Inicio` DATE NOT NULL,
  `Fin` DATE NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  PRIMARY KEY (`Nivel`, `Detalle_TipoUsuario_Codigo`),
  CONSTRAINT `fk_NivelCatedratico_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Director` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Director` (
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NULL,
  `Estado` TINYINT(1) NOT NULL,
  `Escuela_Escuela` INT NOT NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  PRIMARY KEY (`FechaInicio`, `Escuela_Escuela`, `Detalle_TipoUsuario_Codigo`),
  CONSTRAINT `fk_Director_Escuela1`
    FOREIGN KEY (`Escuela_Escuela`)
    REFERENCES `CentroDeCalculo`.`Escuela` (`Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Inscripcion` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Inscripcion` (
  `Fecha` DATE NOT NULL,
  `Escuela_Escuela` INT NOT NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  PRIMARY KEY (`Escuela_Escuela`, `Detalle_TipoUsuario_Codigo`),
  CONSTRAINT `fk_Inscripcion_Escuela1`
    FOREIGN KEY (`Escuela_Escuela`)
    REFERENCES `CentroDeCalculo`.`Escuela` (`Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Seccion` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Seccion` (
  `Seccion` VARCHAR(2) NOT NULL,
  `Cupo` INT NOT NULL,
  `Laboratorio` TINYINT(1) NOT NULL,
  `Ciclo_Anio` INT NOT NULL,
  `Ciclo_Ciclo` INT NOT NULL,
  `Salon_Salon` INT NOT NULL,
  `Salon_Edificio` VARCHAR(4) NOT NULL,
  `Curso_Curso` INT NOT NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  PRIMARY KEY (`Seccion`, `Ciclo_Anio`, `Ciclo_Ciclo`, `Curso_Curso`),
  CONSTRAINT `fk_Seccion_Ciclo1`
    FOREIGN KEY (`Ciclo_Anio` , `Ciclo_Ciclo`)
    REFERENCES `CentroDeCalculo`.`Ciclo` (`Anio` , `Ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_Salon1`
    FOREIGN KEY (`Salon_Salon` , `Salon_Edificio`)
    REFERENCES `CentroDeCalculo`.`Salon` (`Salon` , `Edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_Curso1`
    FOREIGN KEY (`Curso_Curso`)
    REFERENCES `CentroDeCalculo`.`Curso` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Asignacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Asignacion` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Asignacion` (
  `Nota` INT NOT NULL,
  `Zona` INT NOT NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  `Seccion_Seccion` VARCHAR(2) NOT NULL,
  `Seccion_Ciclo_Anio` INT NOT NULL,
  `Seccion_Ciclo_Ciclo` INT NOT NULL,
  `Seccion_Curso_Curso` INT NOT NULL,
  PRIMARY KEY (`Nota`, `Zona`, `Detalle_TipoUsuario_Codigo`, `Seccion_Seccion`, `Seccion_Ciclo_Anio`, `Seccion_Ciclo_Ciclo`, `Seccion_Curso_Curso`),
  CONSTRAINT `fk_Asignacion_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Seccion1`
    FOREIGN KEY (`Seccion_Seccion` , `Seccion_Ciclo_Anio` , `Seccion_Ciclo_Ciclo` , `Seccion_Curso_Curso`)
    REFERENCES `CentroDeCalculo`.`Seccion` (`Seccion` , `Ciclo_Anio` , `Ciclo_Ciclo` , `Curso_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Asignacion_Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Asignacion_Rol` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Asignacion_Rol` (
  `Codigo` INT NOT NULL,
  `Rol` INT NOT NULL,
  PRIMARY KEY (`Codigo`, `Rol`),
  CONSTRAINT `fk_Personal`
    FOREIGN KEY (`Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rol`
    FOREIGN KEY (`Rol`)
    REFERENCES `CentroDeCalculo`.`Rol` (`Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Unidad_NoAcademica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Unidad_NoAcademica` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Unidad_NoAcademica` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fundacion` DATE NOT NULL,
  `Apertura` TIME NOT NULL,
  `Cierre` TIME NOT NULL,
  `Salon_Salon` INT NOT NULL,
  `Salon_Edificio` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`Codigo`),
  CONSTRAINT `fk_Unidad_NoAcademica_Salon1`
    FOREIGN KEY (`Salon_Salon` , `Salon_Edificio`)
    REFERENCES `CentroDeCalculo`.`Salon` (`Salon` , `Edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Asignacion_Personal_UnidadNA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Asignacion_Personal_UnidadNA` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Asignacion_Personal_UnidadNA` (
  `Estado` TINYINT(1) NOT NULL,
  `Area` INT NOT NULL,
  `Unidad_NoAcademica_Codigo` INT NOT NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  PRIMARY KEY (`Unidad_NoAcademica_Codigo`, `Detalle_TipoUsuario_Codigo`),
  CONSTRAINT `fk_Area`
    FOREIGN KEY (`Area`)
    REFERENCES `CentroDeCalculo`.`Area` (`Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Personal_UnidadNA_Unidad_NoAcademica1`
    FOREIGN KEY (`Unidad_NoAcademica_Codigo`)
    REFERENCES `CentroDeCalculo`.`Unidad_NoAcademica` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Personal_UnidadNA_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Asignacion_Personal_Escuela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Asignacion_Personal_Escuela` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Asignacion_Personal_Escuela` (
  `Estado` TINYINT(1) NOT NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  `Escuela_Escuela` INT NOT NULL,
  PRIMARY KEY (`Detalle_TipoUsuario_Codigo`, `Escuela_Escuela`),
  CONSTRAINT `fk_Asignacion_Personal_Escuela_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Personal_Escuela_Escuela1`
    FOREIGN KEY (`Escuela_Escuela`)
    REFERENCES `CentroDeCalculo`.`Escuela` (`Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CentroDeCalculo`.`Director_Unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CentroDeCalculo`.`Director_Unidad` ;

CREATE TABLE IF NOT EXISTS `CentroDeCalculo`.`Director_Unidad` (
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NULL,
  `Estado` TINYINT(1) NOT NULL,
  `Unidad_NoAcademica_Codigo` INT NOT NULL,
  `Detalle_TipoUsuario_Codigo` INT NOT NULL,
  PRIMARY KEY (`Unidad_NoAcademica_Codigo`, `Detalle_TipoUsuario_Codigo`),
  CONSTRAINT `fk_Director_Unidad_Unidad_NoAcademica1`
    FOREIGN KEY (`Unidad_NoAcademica_Codigo`)
    REFERENCES `CentroDeCalculo`.`Unidad_NoAcademica` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_Unidad_Detalle_TipoUsuario1`
    FOREIGN KEY (`Detalle_TipoUsuario_Codigo`)
    REFERENCES `CentroDeCalculo`.`Detalle_TipoUsuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
